services:
  builder:
    build:
      context: ./docker
    volumes:
      - ./:/project
      - nuget_cache:/root/.nuget/packages
    working_dir: /project
    environment:
      HL2SDKCS2: /project/vendor/hl2sdk-cs2
      MMSOURCE112: /project/vendor/metamod-source
    command: >
      bash -c "
        premake5 gmake2 &&
        cd build &&
        make -j$(nproc) &&
        cd ../ &&

        dotnet publish ./managed/AcceleratorCSS_CSS/AcceleratorCSS_CSS.csproj -c Release -o bin/Debug/AcceleratorCSS_CSS &&

        cp configs/addons/metamod/AcceleratorCSS.vdf bin/Debug/ &&
        cp configs/addons/AcceleratorCSS/config.json bin/Debug/
      "

volumes:
  nuget_cache: